"""fixed naming conventions

Revision ID: 038f33e5f465
Revises: 13c0008a11e1
Create Date: 2026-09-28 21:43:41.084048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038f33e5f465'
down_revision: Union[str, Sequence[str], None] = '13c0008a11e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bot_chats_bot_id_fkey'), 'bot_chats', type_='foreignkey')
    op.alter_column('bots', 'id', new_column_name='bot_id', existing_type=sa.Integer(), existing_nullable=False)
    op.drop_index(op.f('ix_bots_id'), table_name='bots')
    op.create_index(op.f('ix_bots_bot_id'), 'bots', ['bot_id'], unique=False)
    op.alter_column('bot_chats', 'id', new_column_name='bot_chat_log_id', existing_type=sa.Integer(), existing_nullable=False)
    op.drop_index(op.f('ix_bot_chats_id'), table_name='bot_chats')
    op.create_index(op.f('ix_bot_chats_bot_chat_log_id'), 'bot_chats', ['bot_chat_log_id'], unique=False)
    op.create_foreign_key(op.f('bot_chats_bot_id_fkey'), 'bot_chats', 'bots', ['bot_id'], ['bot_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bot_chats_bot_id_fkey'), 'bot_chats', type_='foreignkey')
    op.drop_index(op.f('ix_bot_chats_bot_chat_log_id'), table_name='bot_chats')
    op.alter_column('bot_chats', 'bot_chat_log_id', new_column_name='id', existing_type=sa.Integer(), existing_nullable=False)
    op.create_index(op.f('ix_bot_chats_id'), 'bot_chats', ['id'], unique=False)
    op.drop_index(op.f('ix_bots_bot_id'), table_name='bots')
    op.alter_column('bots', 'bot_id', new_column_name='id', existing_type=sa.Integer(), existing_nullable=False)
    op.create_index(op.f('ix_bots_id'), 'bots', ['id'], unique=False)
    op.create_foreign_key(op.f('bot_chats_bot_id_fkey'), 'bot_chats', 'bots', ['bot_id'], ['id'])
    # ### end Alembic commands ###
