"""changed the excursions table name to activity_logs

Revision ID: 52996b2f964f
Revises: f7a820bfdf6a
Create Date: 2026-09-16 23:41:53.884166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52996b2f964f'
down_revision: Union[str, Sequence[str], None] = 'ba5e547ab243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('activity_log_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('net_expenditure', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('activity_log_id')
    )
    op.create_index(op.f('ix_activity_logs_activity_log_id'), 'activity_logs', ['activity_log_id'], unique=False)
    op.drop_index(op.f('ix_excursions_excursion_id'), table_name='excursions')
    op.drop_table('excursions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excursions',
    sa.Column('excursion_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('net_expenditure', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], name=op.f('excursions_activity_id_fkey')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], name=op.f('excursions_group_id_fkey')),
    sa.PrimaryKeyConstraint('excursion_id', name=op.f('excursions_pkey'))
    )
    op.create_index(op.f('ix_excursions_excursion_id'), 'excursions', ['excursion_id'], unique=False)
    op.drop_index(op.f('ix_activity_logs_activity_log_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
