"""create initial schema

Revision ID: 92c7b4c51273
Revises: 
Create Date: 2026-09-16 22:02:06.854506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c7b4c51273'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expenditure', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index(op.f('ix_activities_activity_id'), 'activities', ['activity_id'], unique=False)
    op.create_table('platforms',
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('platform_id')
    )
    op.create_index(op.f('ix_platforms_platform_id'), 'platforms', ['platform_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('accounts',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('date_joined', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.platform_id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('platform_id', 'username', name='unique_platform_account')
    )
    op.create_index(op.f('ix_accounts_account_id'), 'accounts', ['account_id'], unique=False)
    op.create_table('debts',
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('creditor_id', sa.Integer(), nullable=True),
    sa.Column('debtor_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('satisified', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['creditor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['debtor_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('debt_id')
    )
    op.create_index(op.f('ix_debts_debt_id'), 'debts', ['debt_id'], unique=False)
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.String(), nullable=True),
    sa.Column('parent_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['parent_group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_groups_group_id'), 'groups', ['group_id'], unique=False)
    op.create_table('excursions',
    sa.Column('excursion_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('net_expenditure', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('excursion_id')
    )
    op.create_index(op.f('ix_excursions_excursion_id'), 'excursions', ['excursion_id'], unique=False)
    op.create_table('members',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_joined', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('group_id', 'user_id', name='unique_group_member')
    )
    op.create_index(op.f('ix_members_member_id'), 'members', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_member_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_excursions_excursion_id'), table_name='excursions')
    op.drop_table('excursions')
    op.drop_index(op.f('ix_groups_group_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_debts_debt_id'), table_name='debts')
    op.drop_table('debts')
    op.drop_index(op.f('ix_accounts_account_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_platforms_platform_id'), table_name='platforms')
    op.drop_table('platforms')
    op.drop_index(op.f('ix_activities_activity_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
