"""updated tables

Revision ID: 94e198537c2c
Revises: 52996b2f964f
Create Date: 2026-09-19 23:29:14.492300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e198537c2c'
down_revision: Union[str, Sequence[str], None] = '52996b2f964f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['user_id'])
    op.add_column('platforms', sa.Column('url', sa.String(), nullable=True))
    op.drop_column('platforms', 'website')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('unique_user', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user', 'users', type_='unique')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('platforms', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('platforms', 'url')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'user_id')
    # ### end Alembic commands ###
