"""change dates to datetime date

Revision ID: ba5e547ab243
Revises: e8b73ab876c4
Create Date: 2026-09-16 23:18:44.643056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5e547ab243'
down_revision: Union[str, Sequence[str], None] = 'e8b73ab876c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('active_status', sa.Boolean(), nullable=False))
    op.drop_column('accounts', 'date_joined')
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               postgresql_using='date_of_birth::date',
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               postgresql_using='date_of_birth::text',
               nullable=True)
    op.add_column('accounts', sa.Column('date_joined', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('accounts', 'active_status')
    # ### end Alembic commands ###
