"""updated debts and activities tables

Revision ID: db8bb5de5412
Revises: 94e198537c2c
Create Date: 2026-09-21 14:03:21.633218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8bb5de5412'
down_revision: Union[str, Sequence[str], None] = '94e198537c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('date_created', sa.Date(), nullable=True))
    op.alter_column('activities', 'expenditure',
               existing_type=sa.BIGINT(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='CASE WHEN expenditure = 0 THEN FALSE WHEN expenditure IS NULL THEN NULL ELSE TRUE END')
    op.add_column('activity_logs', sa.Column('date_created', sa.Date(), nullable=True))
    op.add_column('activity_logs', sa.Column('net_gain', sa.BigInteger(), nullable=True))
    op.drop_column('activity_logs', 'net_expenditure')
    op.drop_column('activity_logs', 'date')
    op.add_column('debts', sa.Column('activity_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_debts_activity_log_id_activity_logs',
        'debts',
        'activity_logs',
        ['activity_log_id'],
        ['activity_log_id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_debts_activity_log_id_activity_logs',
        'debts',
        type_='foreignkey',
    )
    op.drop_column('debts', 'activity_log_id')
    op.add_column('activity_logs', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activity_logs', sa.Column('net_expenditure', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('activity_logs', 'net_gain')
    op.drop_column('activity_logs', 'date_created')
    op.alter_column('activities', 'expenditure',
               existing_type=sa.Boolean(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               postgresql_using='expenditure::integer')
    op.drop_column('activities', 'date_created')
    # ### end Alembic commands ###
