"""added nickname option in members table

Revision ID: e8b73ab876c4
Revises: 92c7b4c51273
Create Date: 2026-09-16 22:59:07.298522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b73ab876c4'
down_revision: Union[str, Sequence[str], None] = '92c7b4c51273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('nickname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'nickname')
    # ### end Alembic commands ###
